import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/favorites.module.css";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import Header from "../components/header";
import Footer from "../components/footer";
import db from '../db'
import useLogout from "../hooks/useLogout";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }

    const allDrinks = await db.drink.getAllFavoriteDrinks(req.session.user._id)
    
    if(allDrinks?.length){
      props.allDrinks = allDrinks
    }
      
    return { props };
  },
  sessionOptions
);

export default function Favorites(props) {
  const router = useRouter();
  const logout = useLogout();

  return (
    <div >
      <Head>
        <title>Favorite Drinks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props.user.username} image={"/Favorites.jpg"}/>

      <main className={styles.container}>
            
        <div className={styles.searchButton}>
          <Link href="/search">
            <h2>Search for a NEW Drink</h2>
          </Link>
        </div>

        <h1 className={styles.favoritesTitle}>
          Favorites Page!
        </h1>
      
        <div className={styles.favoritesContainer}>
          {props.allDrinks ? (
            <>
                {props.allDrinks.map((drink, i) => (
                  <FavoriteDrink 
                    key={i}
                    id={drink.cocktailDbId} 
                    name={drink.name} 
                    image={drink.image}>
                  </FavoriteDrink>
                ))}
            </>
          ):( 
            <>
              <p >No favorite drinks</p>
            </>
          )}

        </div>
        
      </main>

      <Footer/>
       
    </div>
  );
}


function FavoriteDrink({id, name, image}) {
  const noImage = "/No_image_available.svg.png"
  return (
    <div className={styles.favoriteDrinkCard }>
      <Link href={'/drink/' + id} className={styles.favoriteDrink}>
        <h1 className={styles.favoriteDrinkName}>{name}</h1>
        <Image src={image ? image : noImage} width="200" height="200" alt="picture" className={styles.favoriteDrinkIMG}/>
        <span></span>
      </Link>
    </div>  
    
  )
}
