import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import Footer from "../components/footer";
import useLogout from "../hooks/useLogout";


export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Home(props) {
  const router = useRouter();
  const logout = useLogout();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Tipsy Spirits
        </h1>

        <div>
          {props.isLoggedIn ? (
            <>
              <p className={styles.description}>
                Here is the drink of the day
              </p>
            </>
          ): (
            <>
              <p className={styles.description}>
                Log in or Sign Up!
              </p>
            </>
          )}
        </div>
       

        <div className={styles.grid}>
          {props.isLoggedIn ? (
            <>
              <Link href="/favorites" className={styles.card}>
                <h2>My Favorites</h2>
              </Link>
  
            </>
          ) : (
            <>
              <Link href="/login" className={styles.card}>
                <h2>Login </h2>
              </Link>

              <Link href="/signup" className={styles.card}>
                <h2>Sign Up </h2>
              </Link>
            </>
          )}
        </div>
      </main>

      <Footer/>
    </div>
  );
}
