import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import Footer from "../components/footer";
import { getRandomDrink } from "../util/drinks";


export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }

  const randomDrink = await getRandomDrink()
  if(randomDrink){
    props.randomDrink = randomDrink
  } 
    return { props };
  },
  sessionOptions
);


export default function Home(props) {
  const router = useRouter();
  const randomDrink = props.randomDrink //an array of drinks

  return (
    <div >
      <Head>
        <title>Tipsy Spirits</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} image={"/HomePage.jpg"}/>

      <main >
        
        <div className={styles.container}>
          {props.isLoggedIn ? (
            <>
              <h1 className={styles.drinkSpecialTitle}>
                Drink Special
              </h1>
              <div className={styles.randomDrinkContainer}>
              {randomDrink
                //If random drink exists
                ? <section>
                  {randomDrink.map((drink, i) => (
                    <RandomDrink 
                      key={i}
                      id={drink.cocktailDbId} 
                      name={drink.name} 
                      image={drink.image}>
                    </RandomDrink>
                  ))}
                </section>
                  //If no drinks found, display message
                : <p>No Drinks Found!</p>
              }
              </div>

                <Link href="/favorites" className={styles.favoritesButton}>
                  <h2>My Favorites</h2>
                </Link>
                
            </>
          ) : (
            <>
              <div className={styles.welcomeTitleContainer}>
                <h2 className={styles.subWelcomeTitle}>
                  Welcome to
                </h2>
                <h2 className={styles.welcomeTitle}>
                  Tipsy Spirits
                </h2>
              </div>
              
              <div className={styles.welcomeButtonContainer}>
                  <Link href="/login" className={styles.welcomeButton}>
                    <h2>Login </h2>
                  </Link>

                  <Link href="/signup" className={styles.welcomeButton }>
                    <h2>Sign Up </h2>
                  </Link>
              </div>
            </>
          )}
        </div>
      </main>

      <Footer/>
    </div>
  );
}

function RandomDrink({id, name, image}) {
  const noImage = "/No_image_available.svg.png"
  return (
      <Link href={'/drink/' + id} className={styles.randomDrink}>
        <h1 className={styles.randomDrinkName}>{name}</h1>
        <Image src={image ? image : noImage} width="300" height="300" alt="picture" className={styles.randomDrinkIMG}/>
        <span></span>
      </Link>
    
  )
}